#Setup ----
library(ggplot2)
library(magrittr)
library(purrr)
library(R.matlab)
library(tidyr)
library(dplyr)

#Modeling results files were generated by repo at:
# https://github.com/jeremymoore558/ks_phage

#Read in modeling results data ----
data <- lapply(
  X = grep(pattern = "Analysis.*/.*.csv", value = TRUE,
           x = list.files("./Modeling/", recursive = TRUE, full.names = TRUE)),
  FUN = read.csv)
#Add names
names(data) = 
  gsub(
    pattern = "\\.csv", replacement = "",
    x = gsub(
      pattern = "\\./Modeling/", replacement = "",
      x = grep(
        pattern = "Analysis.*/.*.csv", value = TRUE,
        x = list.files("./Modeling/", recursive = TRUE, full.names = TRUE))))

#Calculate "relative resistance" col
data <- lapply(X = data,
               FUN = function(x) {
                 if("relativeI" %in% colnames(x)) {
                   cbind(x, data.frame("relativeR" = 1/x[, "relativeI"]))
                 } else {return(x)}})

#Add cols for phage distribution and variables manipulated
for (i in 1:length(data)) {
  data[[i]] <- 
    cbind(data.frame(phage_disp = 
                       strsplit(
                         strsplit(names(data)[i], split = "/")[[1]][1], 
                         split = "_")[[1]][2]),
          data[[i]])
  
  myname <- gsub("_b", "", strsplit(names(data)[i], split = "/")[[1]][2])
  
  if(myname == "Analysis") {
    data[[i]] <- cbind(data.frame(distrib = "global"), data[[i]])
  } else if (
    myname == "Analysis_GaussPhage") {
    data[[i]] <- cbind(data.frame(distrib = "local"), data[[i]])
  } else if (
    myname == "Analysis_GaussPhage_Wide") {
    data[[i]] <- cbind(data.frame(distrib = "global_gauss"), data[[i]])
  } else if (
    myname == "Analysis_NoPhage") {
    data[[i]] <- cbind(data.frame(distrib = "no_paras"), data[[i]])
  }
  
  data[[i]] <- cbind(
    data.frame(
      vars_manip_1 = strsplit(strsplit(names(data)[i], split = "/")[[1]][3],
                              split = "_")[[1]][1],
      vars_manip_2 = strsplit(strsplit(names(data)[i], split = "/")[[1]][3],
                              split = "_")[[1]][3],
      vars_manip = paste(strsplit(strsplit(names(data)[i], split = "/")[[1]][3],
                                  split = "_")[[1]][1:3], collapse = "_")),
    data[[i]])
}

#Merge data ----
data_mrg <- data %>% reduce(full_join)
data_mrg$Cell2_Cell1 <- data_mrg$Cell2_population/data_mrg$Cell_population

#Write ----
write.csv(data_mrg, "./Clean_Data/Model_output.csv", row.names = FALSE)
