#Setup ----
library(ggplot2)
library(ggtext)
library(magrittr)
library(dplyr)
library(purrr)
library(R.matlab)
library(tidyr)
library(dplyr)

#Modeling results files were generated by repo at:
# https://github.com/jeremymoore558/ks_phage

#Read in modeling results data ----
data <- lapply(
  X = grep(pattern = "Analysis.*/.*.csv", value = TRUE,
           x = list.files("./Modeling/", recursive = TRUE, full.names = TRUE)),
  FUN = read.csv)
#Add names
names(data) = 
  gsub(pattern = "\\./Modeling//", replacement = "",
       x = grep(pattern = "Modeling//(Analysis.*/.*_tot.csv)", value = TRUE,
                x = list.files("./Modeling/", 
                               recursive = TRUE, full.names = TRUE)))

#Calculate "relative resistance" col
data <- lapply(X = data,
               FUN = function(x) {
                 cbind(x, data.frame("relativeR" = 1/x[, "relativeI"]))})

#Add cols for phage distribution and variables manipulated
for (i in 1:length(data)) {
  if(strsplit(names(data)[i], split = "/")[[1]][1] == "Analysis") {
    data[[i]] <- cbind(data.frame(distrib = "global"), data[[i]])
  } else if (
    strsplit(names(data)[i], split = "/")[[1]][1] == "Analysis_GaussPhage") {
    data[[i]] <- cbind(data.frame(distrib = "local"), data[[i]])
  } else if (
    strsplit(names(data)[i], split = "/")[[1]][1] == "Analysis_GaussPhage_Wide") {
    data[[i]] <- cbind(data.frame(distrib = "global_gauss"), data[[i]])
  } else if (
    strsplit(names(data)[i], split = "/")[[1]][1] == "Analysis_NoPhage") {
    data[[i]] <- cbind(data.frame(distrib = "no_paras"), data[[i]])
  }
  
  data[[i]] <- cbind(
    data.frame(
      vars_manip_1 = strsplit(strsplit(names(data)[i], split = "/")[[1]][2],
                              split = "_")[[1]][1],
      vars_manip_2 = strsplit(strsplit(names(data)[i], split = "/")[[1]][2],
                              split = "_")[[1]][3],
      vars_manip = paste(strsplit(strsplit(names(data)[i], split = "/")[[1]][2],
                                  split = "_")[[1]][1:3], collapse = "_")),
    
    data[[i]])
}

#Merge data ----

data_mrg <- data %>% reduce(full_join)
data_mrg$Cell2_Cell1 <- data_mrg$Cell2_population/data_mrg$Cell_population
data_mrg$distrib <- 
  factor(data_mrg$distrib,
         levels = c("no_paras", "local", "global", "global_gauss"))

#Make plots ----
dir.create("Model_plots", showWarnings = FALSE)
for (vars_manip in unique(data_mrg$vars_manip)) {
  myrows <- which(data_mrg$vars_manip == vars_manip)
  my_data <- data_mrg[myrows, ]
  
  #Get limits for log10(Cell2/Cell) across the dift initial distributions
  # (these are more like the labels)
  mybreaks_pretty <- pretty(x = c(-max(abs(log10(my_data$Cell2_Cell1))),
                                  max(abs(log10(my_data$Cell2_Cell1)))), n = 4)
  if(vars_manip == "I_vs_cR") {mybreaks_pretty <- c(-8, -4, 0, 4, 8)}
  #Get bin limits (these are actually used for the bin limits)
  mybreaks <- seq(from = min(mybreaks_pretty), to = max(mybreaks_pretty),
                  length.out = 8)
  
  #axis labels labeller for the non-resistance axis
  axislabeller <-
    as_labeller(c(relativecA = "Relative Attractant Consumption",
                  relativeChi = "Relative Chemotactic Sensitivity",
                  relativecR = "Relative Growth Rate",
                  relativeY = "Relative Growth Yield"))
  
  #facet labels labeller
  facetlabeller <-
    as_labeller(c(global = "Global",
                  local = "Local",
                  global_gauss = "Global (Gaussian)",
                  no_paras = "Control"))
  
  #Make file
  png(
    paste(sep = "", "./Model_plots/", vars_manip, ".png"),
    width = 6, height = 5, units = "in", res = 150)
  #Make plot
  p <-
    ggplot(my_data,
           aes_string(x = "relativeR", 
                      y = paste("relative", my_data$vars_manip_2[1], sep = ""))) +
      geom_contour_filled(aes(z = log10(Cell2_population/Cell_population)),
                          breaks = mybreaks) +
      geom_point(aes(color = log10(Cell2_population/Cell_population)),
                 size = 3) +
      facet_wrap(~distrib, labeller = facetlabeller) +
      scale_x_continuous(trans = "log10",
                         breaks = 10**c(-2, -1, 0, 1, 2),
                         labels = c("0.01", "0.1", "1", "10", "100")) +
      scale_fill_brewer(type = "div", palette = "PiYG", drop = FALSE) +
      scale_color_distiller(name = "Fitness", type = "div", palette = "PiYG",
                            direction = 1, breaks = mybreaks_pretty,
                             limits = c(min(mybreaks), max(mybreaks))) +
      guides(fill = "none") +
      labs(x = "Relative Resistance") +
      #theme_bw() +
      NULL
  if(vars_manip == "I_vs_Y") {
    p <- p + 
      scale_y_continuous(trans = "log2", breaks = 2**c(-.5, 0, .5),
                         labels = c("-0.5", "0", "0.5"),
                         name = "log<sub>2</sub>(Relative Growth Yield)") +
      theme(axis.title.y = element_markdown())
  } else {p <- p + 
    scale_y_continuous(
      trans = "log2",
      name = axislabeller(paste("relative", my_data$vars_manip_2[1], sep = "")))
  }
  print(p)
  dev.off()
  
  #Make main-text figure
  if(vars_manip == "I_vs_Chi") {
    myrows <- which(data_mrg$vars_manip == vars_manip &
                      data_mrg$distrib %in% c("local", "global", "no_paras"))
    my_data <- data_mrg[myrows, ]
    
    #Get limits for log10(Cell2/Cell) across the dift initial distributions
    # (these are more like the labels)
    mybreaks_pretty <- pretty(x = c(-max(abs(log10(my_data$Cell2_Cell1))),
                                    max(abs(log10(my_data$Cell2_Cell1)))), n = 4)
    #Get bin limits (these are actually used for the bin limits)
    mybreaks <- seq(from = min(mybreaks_pretty), to = max(mybreaks_pretty),
                    length.out = 8)
    
    #Make plot
    png("./Model_plots/I_vs_Chi_maintext.png", width = 8, height = 3, units = "in", res = 150)
    print(
      ggplot(my_data, aes_string(x = "relativeR", y = "relativeChi")) +
        geom_contour_filled(aes(z = log10(Cell2_population/Cell_population)),
                            breaks = mybreaks) +
        geom_point(aes(color = log10(Cell2_population/Cell_population)),
                   size = 3) +
        facet_grid(~distrib, labeller = facetlabeller) +
        scale_x_continuous(trans = "log10",
                           breaks = 10**c(-2, -1, 0, 1, 2),
                           labels = c("0.01", "0.1", "1", "10", "100")) +
        scale_y_continuous(trans = "log2") +
        scale_fill_brewer(type = "div", palette = "PiYG", drop = FALSE) +
        scale_color_distiller(name = "Fitness", type = "div", palette = "PiYG",
                              direction = 1, breaks = mybreaks_pretty,
                              limits = c(min(mybreaks), max(mybreaks))) +
        guides(fill = "none") +
        labs(x = "Relative Resistance", y = "Relative Dispersal") +
        #theme_bw() +
        theme(axis.title.y = element_text(size = 15),
              axis.title.x = element_text(size = 14),
              strip.text.x = element_text(size = 15),
              strip.text.y = element_text(size = 13),
              axis.text.x = element_text(size = 11, angle = 45, hjust = 1),
              axis.text.y = element_text(size = 11)) +
        NULL
    )
    dev.off()
  }
}

#Read in unsummarized data ----
read_tidy_matfile <- function(filename) {
  require(R.matlab)
  require(tidyr)
  require(dplyr)
  
  input <- readMat(filename)
  
  output <- data.frame(matrix(input$SimParams, nrow = 1))
  colnames(output) <- row.names(input$SimParams) 
  
  dens_cols <- 
    which(names(input) %in% 
          c("rho.phage.store", "rho.cell.store", "rho.cell2.store", "A.store", "R.store"))
  
  for (i in dens_cols) {
    #Rename columns
    colnames(input[[i]]) <- paste0("x_", 1:ncol(input[[i]]))
    
    #Add time column
    input[[i]] <- 
      cbind(matrix(input$t.store, ncol = 1, dimnames = list(NULL, "Time")),
            input[[i]])
    
    #Drop extra rows of duplicate times
    input[[i]] <- input[[i]][!duplicated(input[[i]][, "Time"]), ]
    
    #Pivot longer
    temp <- pivot_longer(as.data.frame(input[[i]]), cols = starts_with("x_"),
                         names_to = "Position", 
                         values_to = names(input)[i])
    temp$Position <- 
      as.numeric(gsub(x = temp$Position, pattern = "x_", replacement = ""))
    
    #Merge into output
    if(i == dens_cols[1]) {output <- cross_join(output, temp)
    } else {output <- right_join(output, temp)}
  }
  
  output <- pivot_longer(output, cols = ends_with(".store"),
                         names_to = "Pop", values_to = "Density")
  
  return(output)
}


mydat <- read_tidy_matfile(
  paste0(
    "./Modeling/Outputs_GaussPhage/OutputsIChi_GaussPhage/",
    "SimI2_1e-14Chi2_1770_3cA2_4_17e-16cR2_2_25e-14Y_12290000000.mat"))

#Make moving wave plot ----
ggplot(filter(mydat), 
              aes(x = Position, y = Density, 
                  color = as.factor(round(Time/3600, 1)))) +
  geom_line(lwd = 1.5, alpha = 0.5) +
  facet_grid(Pop ~ ., scales = "free_y") +
  #scale_y_log10() +
  #coord_cartesian(ylim = c(0.1, NA)) +
  NULL

