#Setup ----
library(ggplot2)
library(ggtext)
library(magrittr)
library(purrr)
library(R.matlab)
library(tidyr)
library(dplyr)

#Modeling results files were generated by repo at:
# https://github.com/jeremymoore558/ks_phage

#Read in modeling results data ----
data_mrg <- read.csv("./Clean_Data/Model_output.csv", stringsAsFactors = FALSE)
data_mrg$distrib <- 
  factor(data_mrg$distrib,
         levels = c("no_paras", "local", "global", "global_gauss"))

#Make plots ----
dir.create("Model_plots", showWarnings = FALSE)
for (vars_manip in unique(data_mrg$vars_manip)) {
  myrows <- which(data_mrg$vars_manip == vars_manip)
  my_data <- data_mrg[myrows, ]
  
  #Get limits for log10(Cell2/Cell) across the dift initial distributions
  # (these are more like the labels)
  if(max(abs(log10(my_data$Cell2_Cell1))) == 0) {
    mybreaks_pretty <- c(0)
    mybreaks <- c(0)
  } else {
    mybreaks_pretty <- pretty(x = c(-max(abs(log10(my_data$Cell2_Cell1))),
                                    max(abs(log10(my_data$Cell2_Cell1)))), n = 4)
    if(vars_manip == "I_vs_cR") {mybreaks_pretty <- c(-8, -4, 0, 4, 8)}
    #Get bin limits (these are actually used for the bin limits)
    mybreaks <- seq(from = min(mybreaks_pretty), to = max(mybreaks_pretty),
                    length.out = 8)
  }
  
  #facet labels labeller
  facetlabeller <-
    labeller(distrib = c(global = "Global",
                         local = "Local",
                         global_gauss = "Global (Gaussian)",
                         no_paras = "Control"),
             phage_disp = as_labeller(
               function(x) {paste0("'Phage diffusion rate = ", x, "μm'^2*'/s'")},
               label_parsed))
  
  #axis labels labeller for the non-resistance axis
  axislabeller <-
    as_labeller(c(relativecA = "Bacterial Invader's Relative Attractant Consumption",
                  relativeChi = "Bacterial Invader's Relative Chemotactic Sensitivity",
                  relativecR = "Bacterial Invader's Relative Growth Rate",
                  relativeY = "Bacterial Invader's Relative Growth Yield",
                  relativeb = "Bacterial Invader's Relative Burst Size"))
  
  xvar <- ifelse(my_data$vars_manip_1[1] == "I" | my_data$vars_manip_2[1] == "I", 
                "I", "b")
  yvar <- ifelse(my_data$vars_manip_1[1] == xvar, 
                my_data$vars_manip_2[1], my_data$vars_manip_1[1])
  xvar <- paste0("relative", xvar)
  if(xvar == "relativeI") {xvar <- "relativeR"}
  yvar <- paste0("relative", yvar)
  
  #Make file
  png(
    paste(sep = "", "./Model_plots/", vars_manip, ".png"),
    width = 10, height = 4.5, units = "in", res = 300)
  p <- ggplot(my_data, aes_string(x = xvar, y = yvar)) +
    scale_fill_distiller(name = "Bacterial\nInvader's\nRelative\nFitness", type = "div", palette = "PiYG",
                         direction = 1, breaks = mybreaks_pretty,
                         limits = c(min(mybreaks), max(mybreaks))) +
    facet_grid(phage_disp~distrib, labeller = facetlabeller) +
    labs(x = ifelse(xvar == "relativeR",
                    "Bacterial Invader's Relative Resistance", 
                    "Bacterial Invader's Relative Burst Size")) +
    theme(panel.background = element_rect(fill = "gray90"),
          panel.grid = element_blank()) +
    NULL

  mywidth <- 0.98*(log10(max(my_data[, xvar])) - log10(min(my_data[, xvar])))/4
  if(xvar == "relativeR") {
    p <- p + scale_x_continuous(trans = "log10",
                       breaks = 10**c(-2, -1, 0, 1, 2),
                       labels = c("0.01", "0.1", "1", "10", "100"))
  } else {
    p <- p + scale_x_continuous(trans = "log10",
                                breaks = 10**c(-1, -0.5, 0, 0.5, 1),
                                labels = c("0.01", "", "1", "", "10"))
  }

  myheight <- 0.96*(log2(max(my_data[, yvar])) - log2(min(my_data[, yvar])))/4
  if(yvar == "relativeY") {
    p <- p +
      scale_y_continuous(
        trans = "log2", breaks = 2**c(-.5, 0, .5),
        labels = c("-0.5", "0", "0.5"),
        name = "log<sub>2</sub>(Bacterial Invader's Relative Growth Yield)") +
      theme(axis.title.y = element_markdown())
  } else  if (yvar == "relativeb") {
    p <- p + scale_y_continuous(trans = "log10",
                                breaks = 10**c(-1, -0.5, 0, 0.5, 1),
                                labels = c("0.01", "", "1", "", "10"),
                                name = "Bacterial Invader's Relative Burst Size")
    myheight <- 0.96*(log10(max(my_data[, yvar])) - log10(min(my_data[, yvar])))/4
  } else {
    p <- p + scale_y_continuous(trans = "log2", name = axislabeller(yvar))
  }
  
  p <- p + geom_tile(aes(fill = log10(Cell2_population/Cell_population)),
                     width = mywidth, height = myheight)
  
  print(p)
  dev.off()
  
  #Make main-text figure 5
  if(vars_manip == "I_vs_Chi") {
    myrows <- which(data_mrg$vars_manip == vars_manip &
                      data_mrg$distrib %in% c("local", "global", "no_paras")
                    & data_mrg$phage_disp == 0)
    my_data <- data_mrg[myrows, ]
    
    #Get limits for log10(Cell2/Cell) across the dift initial distributions
    # (these are more like the labels)
    mybreaks_pretty <- pretty(x = c(-max(abs(log10(my_data$Cell2_Cell1))),
                                    max(abs(log10(my_data$Cell2_Cell1)))), n = 4)
    #Get bin limits (these are actually used for the bin limits)
    mybreaks <- seq(from = min(mybreaks_pretty), to = max(mybreaks_pretty),
                    length.out = 8)
    
    #Make plot
    png("./Model_plots/I_vs_Chi_maintext.png", width = 8, height = 3, units = "in", res = 150)
    print(
      ggplot(my_data, aes_string(x = "relativeR", y = "relativeChi")) +
        geom_tile(aes(fill = log10(Cell2_population/Cell_population)),
                  width = 0.95, height = 1.2) +
        scale_fill_distiller(name = "Bacterial\nInvader's\nRelative\nFitness", type = "div", palette = "PiYG",
                             direction = 1, breaks = mybreaks_pretty,
                             limits = c(min(mybreaks), max(mybreaks))) +
        facet_wrap(~distrib, labeller = facetlabeller) +
        scale_x_continuous(trans = "log10",
                           breaks = 10**c(-2, -1, 0, 1, 2),
                           labels = c("0.01", "0.1", "1", "10", "100")) +
        scale_y_continuous(trans = "log2") +
        labs(x = "Bacterial Invader's\nRelative Resistance", 
             y = "Bacterial Invader's\nRelative Dispersal") +
        theme(axis.title.y = element_text(size = 15),
              axis.title.x = element_text(size = 14),
              strip.text.x = element_text(size = 15),
              strip.text.y = element_text(size = 13),
              axis.text.x = element_text(size = 11, angle = 45, hjust = 1),
              axis.text.y = element_text(size = 11),
              panel.background = element_rect(fill = "gray90"),
              panel.grid = element_blank()) +
        NULL
    )
    dev.off()
  }
}

#Read in unsummarized data ----
read_tidy_matfile <- function(filename) {
  require(R.matlab)
  require(tidyr)
  require(dplyr)
  
  input <- readMat(filename)
  
  output <- data.frame(matrix(input$SimParams, nrow = 1))
  colnames(output) <- row.names(input$SimParams) 
  
  dens_cols <- 
    which(names(input) %in% 
          c("rho.phage.store", "rho.cell.store", "rho.cell2.store", "A.store", "R.store"))
  
  for (i in dens_cols) {
    #Rename columns
    colnames(input[[i]]) <- paste0("x_", 1:ncol(input[[i]]))
    
    #Add time column
    input[[i]] <- 
      cbind(matrix(input$t.store, ncol = 1, dimnames = list(NULL, "Time")),
            input[[i]])
    
    #Drop extra rows of duplicate times
    input[[i]] <- input[[i]][!duplicated(input[[i]][, "Time"]), ]
    
    #Pivot longer
    temp <- pivot_longer(as.data.frame(input[[i]]), cols = starts_with("x_"),
                         names_to = "Position", 
                         values_to = names(input)[i])
    temp$Position <- 
      as.numeric(gsub(x = temp$Position, pattern = "x_", replacement = ""))
    
    #Merge into output
    if(i == dens_cols[1]) {output <- cross_join(output, temp)
    } else {output <- right_join(output, temp)}
  }
  
  output <- pivot_longer(output, cols = ends_with(".store"),
                         names_to = "Pop", values_to = "Density")
  
  return(output)
}

#This is old code to make profile plots of the moving waves
if(FALSE) {
  mydat_C <- read_tidy_matfile(
    paste0(
      "./Modeling/Outputs_NoPhageControl/OutputsIChi/",
      "GaussPhage_SimI2_1e-14Chi2_1770_3cA2_4_17e-16cR2_2_25e-14Y_12290000000.mat"))
  mydat_L <- read_tidy_matfile(
    paste0(
      "./Modeling/Outputs_GaussPhage/OutputsIChi_GaussPhage/",
      "SimI2_1e-14Chi2_1770_3cA2_4_17e-16cR2_2_25e-14Y_12290000000.mat"))
  mydat_G <- read_tidy_matfile(
    paste0(
      "./Modeling/Outputs/OutputsIChi/",
      "GaussPhage_SimI2_1e-14Chi2_1770_3cA2_4_17e-16cR2_2_25e-14Y_12290000000.mat"))
  
  #Make moving wave plot ----
  ggplot(filter(mydat_C), 
         aes(x = Position, y = Density, 
             color = as.factor(round(Time/3600, 1)))) +
    geom_line(lwd = 1.5, alpha = 0.5) +
    facet_grid(Pop ~ Time, scales = "free_y") +
    scale_color_viridis_d() +
    #scale_y_log10() +
    #coord_cartesian(ylim = c(0.1, NA)) +
    NULL
  
  ggplot(filter(mydat_L), 
         aes(x = Position, y = Density, 
             color = as.factor(round(Time/3600, 1)))) +
    geom_line(lwd = 1.5, alpha = 0.5) +
    facet_grid(Pop ~ Time, scales = "free_y") +
    scale_color_viridis_d() +
    #scale_y_log10() +
    #coord_cartesian(ylim = c(0.1, NA)) +
    NULL
  
  ggplot(filter(mydat_G), 
         aes(x = Position, y = Density, 
             color = as.factor(round(Time/3600, 1)))) +
    geom_line(lwd = 1.5, alpha = 0.5) +
    facet_grid(Pop ~ Time, scales = "free_y") +
    scale_color_viridis_d() +
    #scale_y_log10() +
    #coord_cartesian(ylim = c(0.1, NA)) +
    NULL
}

